version: 2
jobs:
    build:
        docker:
            - image: fpco/stack-build:lts
        steps:
            - checkout
            - restore_cache:
                name: Restore Cached Dependencies
                keys:
                    - cci-demo-haskell-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - run:
                name: Resolve/Update Dependencies
                command: stack setup
            - run:
                name: Compile
                command: stack build --fast --test --no-run-tests
            - run:
                name: Test
                command: stack test
            - save_cache:
                name: Cache Dependencies
                key: cci-demo-haskell-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
                paths:
                    - "/root/.stack"
                    - ".stack-work"
            - store_artifacts:
                path: ~/.local/bin/circleci-demo-haskell-exe
                destination: circleci-demo-haskell-exe
